# Generated by Django 2.2 on 2019-04-30 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0003_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='hashtag',
            field=models.TextField(blank=True),
        ),
    ]
